export type ReportLanguage = 'en' | 'id';

export interface ReportDictionary {
  reportTitle: string;
  reportSubtitle: string;
  targetUrlLabel: string;
  dateLabel: string;
  statusLabel: string;
  durationLabel: string;
  executiveSummaryTitle: string;
  executiveSummaryTemplate: (target: string, templatesCount: number, findingsCount: number, durationSec: string) => string;
  severityBreakdownTitle: string;
  tableHeaders: {
    severityLevel: string;
    count: string;
    cvssRange: string;
    descriptionImpact: string;
  };
  severityDescriptions: {
    critical: string;
    high: string;
    medium: string;
    low: string;
    info: string;
  };
  detailedFindingsTitle: string;
  noFindingsMessage: string;
  evidenceLabel: string;
  remediationLabel: string;
  contextualImpactLabel: string;
  aggregatedSubChecksLabel: string;
  cvssVectorLabel: string;
  pathLabel: string;
  cweLabel: string;
  categoryLabel: string;
  footerConfidential: string;
  pageOf: (current: number, total: number) => string;
}

export const REPORT_LOCALES: Record<ReportLanguage, ReportDictionary> = {
  en: {
    reportTitle: 'SECURITY VULNERABILITY AUDIT REPORT',
    reportSubtitle: 'Automated Vulnerability Assessment & DevSecOps Audit Engine (OWASP · CVSS v3.1 / v4.0)',
    targetUrlLabel: 'Target URL',
    dateLabel: 'Date',
    statusLabel: 'Status',
    durationLabel: 'Duration',
    executiveSummaryTitle: 'EXECUTIVE AUDIT SUMMARY',
    executiveSummaryTemplate: (target, templatesCount, findingsCount, durationSec) =>
      `A rigorous security assessment was performed against ${target} in ${durationSec}s. A total of ${templatesCount} automated heuristic test suites and passive inspection vectors were evaluated. The assessment discovered ${findingsCount} root finding(s). Below is the consolidated breakdown of identified vulnerabilities, CVSS exploitability ratings, and defense-in-depth remediation guidelines.`,
    severityBreakdownTitle: 'VULNERABILITY SEVERITY & IMPACT BREAKDOWN',
    tableHeaders: {
      severityLevel: 'Severity Level',
      count: 'Count',
      cvssRange: 'CVSS v3.1 Range',
      descriptionImpact: 'Risk Description & System Impact',
    },
    severityDescriptions: {
      critical: 'Remote Code Execution, Credential Leak, Full Infrastructure Takeover',
      high: 'SQL Injection, Arbitrary Data Exfiltration, Sensitive Directory Exposure',
      medium: 'Reflected Parameters, Insecure CORS Policy, Session Cookie Vulnerabilities',
      low: 'Missing Defensive HTTP Security Headers, Information Leakage, Hardening Gaps',
      info: 'Passive Reconnaissance, robots.txt Disallow Endpoints, Server Banner Disclosure',
    },
    detailedFindingsTitle: 'DETAILED AUDIT FINDINGS & REMEDIATION MATRIX',
    noFindingsMessage: 'No security vulnerabilities or hardening gaps were identified with the active test suites.',
    evidenceLabel: 'Matched Evidence',
    remediationLabel: 'Remediation & Hardening Guide',
    contextualImpactLabel: 'Contextual Risk Correlation',
    aggregatedSubChecksLabel: 'Consolidated Sub-Check Details',
    cvssVectorLabel: 'CVSS Vector',
    pathLabel: 'Endpoint Path',
    cweLabel: 'CWE',
    categoryLabel: 'OWASP Category',
    footerConfidential: 'Confidential DevSecOps Security Audit Report — Generated by Automated Assessment Suite',
    pageOf: (current, total) => `Page ${current} of ${total}`,
  },
  id: {
    reportTitle: 'LAPORAN AUDIT KEAMANAN & KERENTANAN SISTEM',
    reportSubtitle: 'Mesin Pemindai Kerentanan Otomatis & Audit DevSecOps (Standar OWASP · CVSS v3.1 / v4.0)',
    targetUrlLabel: 'URL Sasaran',
    dateLabel: 'Tanggal Audit',
    statusLabel: 'Status',
    durationLabel: 'Durasi',
    executiveSummaryTitle: 'RINGKASAN EKSEKUTIF AUDIT',
    executiveSummaryTemplate: (target, templatesCount, findingsCount, durationSec) =>
      `Audit keamanan menyeluruh telah dilakukan terhadap sistem ${target} dalam waktu ${durationSec} detik. Sebanyak ${templatesCount} suite pengujian otomatis dan vektor inspeksi pasif telah dievaluasi. Proses audit mengidentifikasi ${findingsCount} temuan akar masalah. Berikut rincian klasifikasi risiko, skor eksploitasi CVSS, serta panduan pengerasan keamanan (remediasi) berstandar industri.`,
    severityBreakdownTitle: 'DISTRIBUSI TINGKAT KEPARAHAN & DAMPAK RISIKO',
    tableHeaders: {
      severityLevel: 'Tingkat Keparahan',
      count: 'Jumlah',
      cvssRange: 'Rentang CVSS v3.1',
      descriptionImpact: 'Deskripsi Risiko & Dampak Sistem',
    },
    severityDescriptions: {
      critical: 'Eksekusi Kode Jarak Jauh (RCE), Kebocoran Kredensial, Pengambilalihan Server',
      high: 'SQL Injection, Akses Data Ilegal, Keterpaparan Direktori Sensitif',
      medium: 'Parameter Terfleksi (XSS), Kebijakan CORS Terlalu Terbuka, Celah Sesi',
      low: 'Ketiadaan Header Keamanan HTTP Defensif, Kebocoran Informasi Minimal',
      info: 'Pengintaian Pasif, Endpoint robots.txt, Pengungkapan Banner Server',
    },
    detailedFindingsTitle: 'RINCIAN TEMUAN AUDIT & PANDUAN REMEDIASI',
    noFindingsMessage: 'Tidak ditemukan kerentanan keamanan atau celah konfigurasi pada rangkaian pengujian aktif.',
    evidenceLabel: 'Bukti Temuan (Evidence)',
    remediationLabel: 'Panduan Remediasi & Pengerasan Server',
    contextualImpactLabel: 'Korelasi Risiko Kontekstual',
    aggregatedSubChecksLabel: 'Rincian Sub-Pemeriksaan Terkonsolidasi',
    cvssVectorLabel: 'Vektor CVSS',
    pathLabel: 'Jalur Endpoint',
    cweLabel: 'CWE',
    categoryLabel: 'Kategori OWASP',
    footerConfidential: 'Laporan Rahasia Audit Keamanan DevSecOps — Dihasilkan oleh Mesin Penilaian Otomatis',
    pageOf: (current, total) => `Halaman ${current} dari ${total}`,
  },
};
